### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found on WINDOWS

### ISSUE THREAD

**Issue by gasgallo** [google-coral/tflite#10]
I'm trying to run python examples on Windows 10. EdgeTPU setup seems successfull, the device is detected in device manager. But when I try to run one of the examples, I get the error as in the title:
```bash
OSError: [WinError 126] The specified module could not be found
```
followed by:
```bash
AttributeError: 'Delegate' object has no attribute '_library'
```
The full log:
```bash
Traceback (most recent call last):
  File "classify_image.py", line 108, in <module>
    main()
  File "classify_image.py", line 85, in main
    interpreter = make_interpreter(args.model)
  File "classify_image.py", line 68, in make_interpreter
    tflite.load_delegate(EDGETPU_SHARED_LIB, {'device': device[0]} if device else {})])
  File "C:\Users\gasgallo\AppData\Local\Programs\Python\Python37\lib\site-packages\tflite_runtime\interpreter.py", line 162, in load_delegate
    delegate = Delegate(library, options)
  File "C:\Users\gasgallo\AppData\Local\Programs\Python\Python37\lib\site-packages\tflite_runtime\interpreter.py", line 91, in __init__
    self._library = ctypes.pydll.LoadLibrary(library)
  File "C:\Users\gasgallo\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\gasgallo\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
Exception ignored in: <function Delegate.__del__ at 0x00000270FC36A4C8>
Traceback (most recent call last):
  File "C:\Users\gasgallo\AppData\Local\Programs\Python\Python37\lib\site-packages\tflite_runtime\interpreter.py", line 126, in __del__
    if self._library is not None:
AttributeError: 'Delegate' object has no attribute '_library'
````
If I unplug the edgeTPU and run the same python command, I get exactly the same error, so it's like the device isn't detected by `tflite-runtime` or `tflite-runtime` fails to load some dependencies?

Any idea?

**Comment by gasgallo** [comment]
I didn't update `EDGETPU_SHARED_LIB` to the proper library..
