### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by julio8a** [google-coral/tflite#36]
I followed this tutorial and it was able to classify the image just fine.
https://coral.ai/docs/accelerator/get-started/

However, when I try and run object detection through the readme on here I get this error. I'm on a Raspberry Pi4

```
Traceback (most recent call last):
  File "detect_image.py", line 129, in <module>
    main()
  File "detect_image.py", line 94, in main
    interpreter = make_interpreter(args.model)
  File "detect_image.py", line 61, in make_interpreter
    {'device': device[0]} if device else {})
  File "/home/pi/.local/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 204, in __init__
    model_path, self._custom_op_registerers))
ValueError: Model provided has model identifier '
<!D', should be 'TFL3'
```

FYI, I'm a total newbie to this.

**Comment by julio8a** [comment]
I think this is related to #24

**Comment by julio8a** [comment]
I did download the files manually, but I get another value error saying could not open.

```
Traceback (most recent call last):
  File "detect_image.py", line 129, in <module>
    main()
  File "detect_image.py", line 94, in main
    interpreter = make_interpreter(args.model)
  File "detect_image.py", line 61, in make_interpreter
    {'device': device[0]} if device else {})
  File "/home/pi/.local/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 204, in __init__
    model_path, self._custom_op_registerers))
ValueError: Could not open 'models/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite'.
```

![image](https://user-images.githubusercontent.com/6144462/96910212-fa5a6000-1453-11eb-891f-b1f8a7cf65f9.png)

**Comment by Namburger** [comment]
@julio8a this will be fixed within the next couple weeks, but anyways, when you run the code, you also need to change the model file from mobilenet_ssd to ssd_mobilenet

**Comment by manoj7410** [comment]
@julio8a Were you able to fix this ?

**Comment by manoj7410** [comment]
Closing this due to lack of activity. Feel free to reopen this thread if the issue still persists.
