### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by Haonan-99** [google-coral/tflite#55]
I get erro when i run classify_capture.py :

mendel@mocha-quill:~/google-coral/examples-camera/pygame$ python3 classify_capture.py
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "classify_capture.py", line 77, in <module>
    main()
  File "classify_capture.py", line 45, in main
    interpreter = make_interpreter(args.model)
  File "/usr/lib/python3/dist-packages/pycoral/utils/edgetpu.py", line 87, in make_interpreter
    delegates = [load_edgetpu_delegate({'device': device} if device else {})]
  File "/usr/lib/python3/dist-packages/pycoral/utils/edgetpu.py", line 52, in load_edgetpu_delegate
    return tflite.load_delegate(_EDGETPU_SHARED_LIB, options or {})
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 163, in load_delegate
    library, str(e)))
ValueError: Failed to load delegate from libedgetpu.so.1

I was follwed the directions exactly:) can someone help me?

**Comment by manoj7410** [comment]
@Elias9898 Which Coral board are you using ?

**Comment by hjonnala** [comment]
Hello @Elias9898 The error is due to you might have stopped earlier any script with ctrl+z. If this is the case please reboot the board and try the script. Or somehow libedgetpu1-std package is missing. Please try to install libedgetpu1-std package and try the demo. Thanks!

https://coral.ai/software/#debian-packages
