### ISSUE TITLE
pycoral has problem -- Edge TPU

### ISSUE THREAD

**Issue by hyeonseochoi2006** [google-coral/tflite#66]
### Description

chuih@▒▒▒▒_NOTE-BOOK MINGW64 ~/coral/pycoral (master)
$ python3 examples/classify_image.py \
--model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite \
--labels test_data/inat_bird_labels.txt \
--input test_data/parrot.jpg
Traceback (most recent call last):
  File "C:\Users\chuih\coral\pycoral\examples\classify_image.py", line 121, in <module>
    main()
  File "C:\Users\chuih\coral\pycoral\examples\classify_image.py", line 79, in main
    image = Image.open(args.input).convert('RGB').resize(size, Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

and i have python version 3.9.0

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Relevant Log Output

_No response_</details>

**Comment by hyeonseochoi2006** [comment]
coral setup => https://coral.ai/docs/accelerator/get-started/#pycoral-on-linux
